# Generated by zix from zix/managed/manifest.json - do not edit by hand.
# Add or remove entries with:
#   nix run .#zix -- pkg add NAME      (target: managed = every host)
#   nix run .#zix -- pkg rm NAME
{ pkgs }:
with pkgs;
[
]
