# Generated by zix from zix/managed/manifest.json - do not edit by hand.
# Add or remove entries with:
#   zix add NAME      (target: managed = every host)
#   zix rm NAME
{ pkgs }:
with pkgs;
[
  caddy
]
